- hosts: all
  tags: prereq
  become: yes
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux
    # kernel install reboots anyway
    
    - name: Install patched kernels for lustre
      import_role:
        name: ansible-role-linux-kernel

- hosts: servers
  tags: servers
  become: yes
  tasks:
    - name: Enumerate devices
      lsbkl:
      register: lsblk
      changed_when: false
    - debug:
        var: lsblk
    - assert:
        that:
          - lsblk.devices['45da89db-6c07-461e-a'] == '/dev/sdb' # MGS
          - lsblk.devices['5394d5fe-4dda-44a5-a'] == '/dev/sdc' # MDT
          - lsblk.devices['c51788e8-9660-4487-b'] == '/dev/sdd' # OST
    - name: Install lustre server
      import_role:
        name: ansible-role-lustre
